version: '2'
services:
    shoppyngapp-app:
        image: shoppyngapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shoppyngapp-mysql:3306/shoppyngapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shoppyngapp-mysql:
        extends:
            file: mysql.yml
            service: shoppyngapp-mysql
